version: '3'

services:
  donation_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: donation_client
    container_name: donation_client
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
    networks:
      - app-network

  donation_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: donation_server
    container_name: donation_server
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "4000:8080"
    volumes:
      - ./server:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/ts-node ./src/index.ts

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./server/dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
